Create server app.
VitalySokolov/nodejs-learning-project pull request #3
Opened 2019-02-11 19:34 UTC by VitalySokolov

2019-02-18 19:34 UTC, pavel-ulasavets requested changes
In general the homework is done well (thank you for that btw:)) The only comment which I'd like to be fixed is a separation of data model operations and routing logic cause (and I believe you know it) these are two different responsibilities and it will be complicated as hell to maintain that code in future

2019-02-18 19:34 UTC, pavel-ulasavets commented on src/middlewares/cookieParser.js
> +    cookieString.split(';')
Minor: Array.prototype.reduce might work well in this circumstances

2019-02-18 19:34 UTC, pavel-ulasavets commented on src/routes/products.js
> +const products = [
In general, it is not the best idea to mix data layer together with router logic. From my perspective it is much better to create a separate module which will be responsible for returning the data as well as data validation upon adding/removing entries

2019-02-19 19:49 UTC, VitalySokolov commented on src/middlewares/cookieParser.js
> +    cookieString.split(';')
Thanks for tip. Will try to refactor this in the next PR.

2019-02-19 19:52 UTC, VitalySokolov commented on src/routes/products.js
> +const products = [
Absolutely agree. It was done with fake data only as example that it'll be working.
I already moved data and validation logic to the separate module in the next PR.

2019-02-19 20:18 UTC, pavel-ulasavets approved these changes

2019-02-20 22:50 UTC, merged